[tool.poetry]
name = "first-block"
version = "0.1.0"
description = "Basics of Python"
authors = ["c3equalz <dan.kovalev2013@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
