services:
  postgres:
    image: postgres
    container_name: postgres-third-block
    hostname: ${DATABASE_HOST}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend
    env_file:
      - ../.env

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    container_name: pgadmin-third-block
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      postgres:
        condition: service_healthy
    user: root
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      - backend
    env_file:
      - ../.env

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge